name: Terraform CI/CD

on:
  push:
    paths:
      - 'dev/*.tf'
      - 'prod/*.tf'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check changed directories
      id: get-changed-dir
      run: |
        changed_folders=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '.tf' | sed -E 's@(.+)/.*@\1@' | uniq)
        echo "Changed folders: $changed_folders"
        echo "::set-output name=dirs::$changed_folders"

    - name: Set matrix for next job
      id: set-matrix
      run: |
        echo "::set-output name=matrix::{\"include\": [$(echo '"$changed_folders"' | sed 's/ /", "/g' | awk '{print "{\"environment\":\""$1"\"}"}')]}"

  terraform:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.detect-changes.outputs.matrix)}}
    defaults:
      run:
        working-directory: ${{ matrix.environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: terraform apply -auto-approve
