name: Infra cicd

on:
  pull_request:
    branches:
      - main
      - 'feature/**'
    paths:
      - 'tf-rg/*.tf'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Detect Changed Terraform Directories
        id: get-changed-dir
        run: |
          changed_folders=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '.tf' | sed -E 's@(.+)/.*@\1@' | uniq)
          echo "Changed folders: $changed_folders"
          echo "changed_folders=$changed_folders" >> $GITHUB_ENV

      - name: Prepare Matrix for Terraform Job
        id: set-matrix
        run: |
          matrix_data=$(echo "$changed_folders" | sed 's/ /", "/g' | awk '{print "{\"environment\":\""$1"\"}"}')
          echo "::set-output name=matrix::[ $matrix_data ]"

  terraform:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(steps.set-matrix.outputs.matrix)}}
    defaults:
      run:
        working-directory: ${{ matrix.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.7

      - name: Terraform Initialization
        run: terraform init -backend-config=${{ matrix.environment }}/backend-config.hcl

      - name: Terraform Plan
        run: terraform plan -var-file="${{ matrix.environment }}/terraform.tfvars"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -var-file="${{ matrix.environment }}/terraform.tfvars" -auto-approve
